---
all:
  children:
    docker_rootless_hosts:
      children:
        docker_rootless_remote_hosts:
          vars:
            ansible_user: root
          hosts:
            ubuntu25:
              ansible_host: 192.168.1.76
            # Add additional remote hosts here.
            # debian12-app-01:
            #   ansible_host: 192.168.1.81
            # ubuntu24-db-01:
            #   ansible_host: 192.168.1.82
        docker_rootless_local_hosts:
          vars:
            ansible_connection: local
            ansible_user: root
          hosts:
            localhost:
              ansible_host: 127.0.0.1
