---
all:
  children:
    podman_rootless_hosts:
      children:
        podman_rootless_remote_hosts:
          vars:
            ansible_user: root
          hosts:
            debian12:
              ansible_host: 192.168.1.64
            # Add additional remote hosts here.
#        podman_rootless_local_hosts:
#          vars:
#            ansible_connection: local
#            ansible_user: root
#          hosts:
#            localhost:
